# Generated by Django 5.2.9 on 2025-12-12 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "conversation_type",
                    models.CharField(
                        choices=[("direct", "Direct Message"), ("group", "Group")],
                        db_index=True,
                        default="group",
                        help_text="Type of conversation (direct or group)",
                        max_length=10,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Title for group conversations (empty for direct)",
                        max_length=100,
                    ),
                ),
                (
                    "participant_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current number of active participants (cached for performance)",
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp of most recent message (for sorting conversation lists)",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this conversation (null for system-created)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_conversation",
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[("text", "Text"), ("system", "System")],
                        db_index=True,
                        default="text",
                        help_text="Type of message (text or system)",
                        max_length=10,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Message content (text for user messages, JSON for system messages)"
                    ),
                ),
                (
                    "reply_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of replies to this message (cached for performance)",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="Conversation this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                    ),
                ),
                (
                    "parent_message",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent message for threading (null if root message)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="chat.message",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who sent this message (null for system messages)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_message",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                        ],
                        db_index=True,
                        help_text="Role in group conversation (null for direct conversations)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the user joined this conversation",
                    ),
                ),
                (
                    "left_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When the user left (null if still active)",
                        null=True,
                    ),
                ),
                (
                    "left_voluntarily",
                    models.BooleanField(
                        blank=True,
                        help_text="True if user left voluntarily, False if removed by someone",
                        null=True,
                    ),
                ),
                (
                    "last_read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time user marked conversation as read (for unread counts)",
                        null=True,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="Conversation this participation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="chat.conversation",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who removed this participant (if removed by someone)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="removed_participants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User participating in the conversation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_participant",
                "ordering": ["joined_at"],
            },
        ),
        migrations.CreateModel(
            name="DirectConversationPair",
            fields=[
                (
                    "conversation",
                    models.OneToOneField(
                        help_text="The direct conversation this pair represents",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="direct_pair",
                        serialize=False,
                        to="chat.conversation",
                    ),
                ),
                (
                    "user_higher",
                    models.ForeignKey(
                        help_text="User with higher ID in this conversation pair",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_lower",
                    models.ForeignKey(
                        help_text="User with lower ID in this conversation pair",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_direct_conversation_pair",
            },
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["conversation_type", "is_deleted"],
                name="chat_conv_type_deleted_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                condition=models.Q(("is_deleted", False)),
                fields=["-last_message_at"],
                name="chat_conv_last_msg_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at", "id"],
                name="chat_msg_conv_cursor_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                condition=models.Q(("parent_message__isnull", False)),
                fields=["parent_message", "created_at"],
                name="chat_msg_parent_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "-created_at"], name="chat_msg_sender_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "message_type"], name="chat_msg_conv_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="participant",
            index=models.Index(
                fields=["conversation", "left_at"], name="chat_part_conv_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="participant",
            index=models.Index(
                fields=["user", "left_at", "-joined_at"],
                name="chat_part_user_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="participant",
            index=models.Index(
                condition=models.Q(("left_at__isnull", True)),
                fields=["conversation", "role", "joined_at"],
                name="chat_part_conv_role_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("left_at__isnull", True)),
                fields=("conversation", "user"),
                name="unique_active_participation",
            ),
        ),
        migrations.AddIndex(
            model_name="directconversationpair",
            index=models.Index(
                fields=["user_lower", "user_higher"], name="chat_direct_pair_users_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="directconversationpair",
            constraint=models.UniqueConstraint(
                fields=("user_lower", "user_higher"),
                name="unique_direct_conversation_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="directconversationpair",
            constraint=models.CheckConstraint(
                condition=models.Q(("user_lower_id__lt", models.F("user_higher_id"))),
                name="user_lower_less_than_higher",
            ),
        ),
    ]
