# Generated by Django 5.2.9 on 2025-12-15 20:57

import django.db.models.deletion
import media.models.media_file
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when this record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible key-value metadata storage",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The uploaded media file",
                        upload_to=media.models.media_file.media_upload_path,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original filename from the upload", max_length=255
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("document", "Document"),
                            ("audio", "Audio"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        help_text="Category of media (image, video, document, audio, other)",
                        max_length=20,
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        help_text="Detected MIME type (e.g., image/jpeg, application/pdf)",
                        max_length=127,
                    ),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("shared", "Shared"),
                            ("internal", "Internal"),
                        ],
                        db_index=True,
                        default="private",
                        help_text="Access level for this file",
                        max_length=20,
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current processing pipeline status",
                        max_length=20,
                    ),
                ),
                (
                    "processing_attempts",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of processing attempts"
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(
                        blank=True,
                        help_text="Error message if processing failed",
                        null=True,
                    ),
                ),
                (
                    "processing_priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                        ],
                        default="normal",
                        help_text="Priority in processing queue",
                        max_length=20,
                    ),
                ),
                (
                    "processing_started_at",
                    models.DateTimeField(
                        blank=True, help_text="When processing started", null=True
                    ),
                ),
                (
                    "processing_completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When processing completed", null=True
                    ),
                ),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("clean", "Clean"),
                            ("infected", "Infected"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Antivirus scan status",
                        max_length=20,
                    ),
                ),
                (
                    "threat_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of detected threat if infected",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "scanned_at",
                    models.DateTimeField(
                        blank=True, help_text="When the file was scanned", null=True
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number of this file"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this is the current version",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        help_text="User who uploaded the file",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to the original file in a version chain",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="media.mediafile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media File",
                "verbose_name_plural": "Media Files",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["uploader", "media_type"],
                        name="media_media_uploade_247111_idx",
                    ),
                    models.Index(
                        fields=["uploader", "created_at"],
                        name="media_media_uploade_f2cb79_idx",
                    ),
                    models.Index(
                        fields=["visibility", "is_current"],
                        name="media_media_visibil_c439b3_idx",
                    ),
                    models.Index(
                        fields=["version_group", "version"],
                        name="media_media_version_a49011_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("file_size__gt", 0)),
                        name="media_file_size_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="media_file_version_at_least_one",
                    ),
                ],
            },
        ),
    ]
