# Generated by Django 5.2.9 on 2025-12-15 21:26

import django.db.models.deletion
import media.models.media_asset
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("thumbnail", "Thumbnail"),
                            ("preview", "Preview"),
                            ("web_optimized", "Web Optimized"),
                            ("poster", "Video Poster"),
                            ("transcoded", "Transcoded Video"),
                            ("low_res", "Low Resolution"),
                            ("pdf_preview", "PDF Preview"),
                            ("extracted_text", "Extracted Text"),
                        ],
                        help_text="Type of generated asset",
                        max_length=30,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="The generated asset file",
                        upload_to=media.models.media_asset.get_asset_upload_path,
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Width in pixels (for images/videos)",
                        null=True,
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Height in pixels (for images/videos)",
                        null=True,
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(help_text="Size of the asset file in bytes"),
                ),
                (
                    "media_file",
                    models.ForeignKey(
                        help_text="Parent media file this asset belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="media.mediafile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Asset",
                "verbose_name_plural": "Media Assets",
                "ordering": ["asset_type", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["media_file", "asset_type"], name="idx_asset_by_type"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("media_file", "asset_type"),
                        name="unique_asset_type_per_media_file",
                    )
                ],
            },
        ),
    ]
