# Generated by Django 5.2.9 on 2025-12-16 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0004_version_group_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="is_current",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether this is the current (active) version",
            ),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Version number of this file (starts at 1 for originals)",
            ),
        ),
        migrations.CreateModel(
            name="MediaFileShare",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "can_download",
                    models.BooleanField(
                        default=True,
                        help_text="Whether recipient can download (vs view-only)",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When this share expires (null = never)",
                        null=True,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional message from the sharer",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "media_file",
                    models.ForeignKey(
                        help_text="The file being shared (version group root)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="media.mediafile",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        help_text="User who created this share",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ForeignKey(
                        help_text="User receiving access to the file",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Media File Share",
                "verbose_name_plural": "Media File Shares",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["shared_with", "expires_at"],
                        name="media_media_shared__12ccc7_idx",
                    ),
                    models.Index(
                        fields=["media_file", "shared_with"],
                        name="media_media_media_f_fa3394_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("media_file", "shared_with"),
                        name="media_share_unique_file_user",
                    )
                ],
            },
        ),
    ]
