# Generated by Django 5.2.9 on 2025-12-16 21:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0005_add_media_file_share"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadSession",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="Original filename of the file being uploaded",
                        max_length=255,
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        help_text="Expected total file size in bytes"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(help_text="MIME type of the file", max_length=100),
                ),
                (
                    "media_type",
                    models.CharField(
                        help_text="Media type category (image, video, document, audio, other)",
                        max_length=20,
                    ),
                ),
                (
                    "backend",
                    models.CharField(
                        choices=[("local", "Local Filesystem"), ("s3", "Amazon S3")],
                        help_text="Storage backend type",
                        max_length=20,
                    ),
                ),
                (
                    "s3_key",
                    models.CharField(
                        blank=True,
                        help_text="S3 object key for the upload (S3 backend only)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "s3_upload_id",
                    models.CharField(
                        blank=True,
                        help_text="S3 multipart upload ID (S3 backend only)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "local_temp_dir",
                    models.CharField(
                        blank=True,
                        help_text="Temporary directory path (local backend only)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "bytes_received",
                    models.BigIntegerField(
                        default=0, help_text="Total bytes received so far"
                    ),
                ),
                (
                    "parts_completed",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of completed parts: [{'part_number': 1, 'etag': '...', 'size': ...}]",
                    ),
                ),
                (
                    "chunk_size",
                    models.PositiveIntegerField(
                        default=5242880, help_text="Size of each chunk in bytes"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("failed", "Failed"),
                        ],
                        default="in_progress",
                        help_text="Current session status",
                        max_length=20,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this session expires"),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        help_text="User who initiated the upload",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["uploader", "status"],
                        name="idx_upload_session_user_status",
                    ),
                    models.Index(
                        fields=["expires_at"], name="idx_upload_session_expires"
                    ),
                    models.Index(
                        fields=["status", "expires_at"],
                        name="idx_upload_session_status_exp",
                    ),
                ],
            },
        ),
    ]
