# Generated by Django 5.2.9 on 2025-12-16 23:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0006_upload_session"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the tag", max_length=100
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe version of the name", max_length=100
                    ),
                ),
                (
                    "tag_type",
                    models.CharField(
                        choices=[
                            ("user", "User Created"),
                            ("system", "System"),
                            ("auto", "Auto-Generated"),
                        ],
                        db_index=True,
                        default="user",
                        help_text="Type of tag (user, system, auto)",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Optional category for grouping (e.g., 'color', 'subject', 'location')",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Hex color code for UI display (e.g., '#FF5733')",
                        max_length=7,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owner of user tags. NULL for system/auto tags.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MediaFileTag",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Confidence score (0.0-1.0) for auto-detected tags",
                        null=True,
                    ),
                ),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who applied this tag. NULL for auto-detected tags.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "media_file",
                    models.ForeignKey(
                        help_text="The media file being tagged",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_tags",
                        to="media.mediafile",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        help_text="The tag applied to the file",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_files",
                        to="media.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media File Tag",
                "verbose_name_plural": "Media File Tags",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["owner", "slug"], name="media_tag_owner_i_86f27b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["tag_type", "category"], name="media_tag_tag_typ_f50048_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner__isnull", False)),
                fields=("slug", "owner"),
                name="tag_unique_user_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner__isnull", True)),
                fields=("slug",),
                name="tag_unique_global_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("owner__isnull", False), ("tag_type", "user")),
                    models.Q(
                        ("owner__isnull", True), ("tag_type__in", ["system", "auto"])
                    ),
                    _connector="OR",
                ),
                name="tag_owner_type_consistency",
            ),
        ),
        migrations.AddIndex(
            model_name="mediafiletag",
            index=models.Index(
                fields=["media_file", "tag"], name="media_media_media_f_ee0584_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediafiletag",
            index=models.Index(
                fields=["tag", "confidence"], name="media_media_tag_id_8acde2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediafiletag",
            index=models.Index(
                fields=["applied_by", "created_at"],
                name="media_media_applied_89a9e2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="mediafiletag",
            constraint=models.UniqueConstraint(
                fields=("media_file", "tag"), name="media_file_tag_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="mediafiletag",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("confidence__isnull", True),
                    models.Q(("confidence__gte", 0.0), ("confidence__lte", 1.0)),
                    _connector="OR",
                ),
                name="media_file_tag_confidence_range",
            ),
        ),
    ]
