# Generated by Django 5.2.9 on 2025-12-16 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0007_add_tag_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                condition=models.Q(("processing_status", "pending")),
                fields=["processing_status", "processing_priority", "created_at"],
                name="idx_processing_queue",
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                condition=models.Q(("scan_status", "pending")),
                fields=["scan_status", "created_at"],
                name="idx_scan_queue",
            ),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(
                condition=models.Q(("is_deleted", False)),
                fields=["uploader", "is_deleted", "-created_at"],
                name="idx_active_files",
            ),
        ),
    ]
