# Generated by Django 5.2.9 on 2026-01-02 18:33

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_add_search_reconciliation_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, help_text='Full-text search vector combining filename, tags, and content', null=True),
        ),
    ]
