# Generated by Django 5.2.9 on 2025-12-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_add_bio_public_key_to_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="storage_quota_bytes",
            field=models.BigIntegerField(
                default=5368709120,
                help_text="Maximum storage allowed for this user in bytes (default 5GB)",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="total_storage_bytes",
            field=models.BigIntegerField(
                default=0, help_text="Total storage used by this user in bytes"
            ),
        ),
    ]
