# Generated by Django 5.2.9 on 2025-12-19 22:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_update_default_storage_quota"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for this record",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
