# Generated by Django 5.2.9 on 2025-12-12 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique programmatic identifier (e.g., 'order_shipped')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name for display", max_length=200
                    ),
                ),
                (
                    "title_template",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Python format string template for title (e.g., '{actor_name} liked your post')",
                        max_length=500,
                    ),
                ),
                (
                    "body_template",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Python format string template for body",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this notification type is currently enabled",
                    ),
                ),
                (
                    "supports_push",
                    models.BooleanField(
                        default=True, help_text="Can be delivered via push notification"
                    ),
                ),
                (
                    "supports_email",
                    models.BooleanField(
                        default=False, help_text="Can be delivered via email"
                    ),
                ),
                (
                    "supports_websocket",
                    models.BooleanField(
                        default=True, help_text="Can be broadcast via WebSocket"
                    ),
                ),
            ],
            options={
                "verbose_name": "notification type",
                "verbose_name_plural": "notification types",
                "db_table": "notifications_notification_type",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Fully rendered notification title", max_length=500
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Fully rendered notification body",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary context data (deep links, metadata)",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="ID of source object", null=True
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether recipient has read this notification",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered this notification (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Content type of source object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="User receiving this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notification_type",
                    models.ForeignKey(
                        help_text="Type of this notification",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="notifications.notificationtype",
                    ),
                ),
            ],
            options={
                "db_table": "notifications_notification",
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "-created_at"],
                        name="notif_recipient_unread_idx",
                    ),
                    models.Index(
                        fields=["recipient", "notification_type"],
                        name="notif_recipient_type_idx",
                    ),
                ],
            },
        ),
    ]
