# Generated by Django 5.2.9 on 2025-12-12 21:09

from django.db import migrations


def seed_notification_types(apps, schema_editor):
    """
    Seed initial notification types.

    These are common notification types that most applications need.
    Add or modify based on your domain requirements.
    """
    NotificationType = apps.get_model("notifications", "NotificationType")

    notification_types = [
        {
            "key": "welcome",
            "display_name": "Welcome",
            "title_template": "Welcome to the app!",
            "body_template": "Thanks for joining. We're excited to have you.",
            "is_active": True,
            "supports_push": True,
            "supports_email": True,
            "supports_websocket": False,
        },
        {
            "key": "new_message",
            "display_name": "New Message",
            "title_template": "New message from {sender_name}",
            "body_template": "{preview}",
            "is_active": True,
            "supports_push": True,
            "supports_email": False,
            "supports_websocket": True,
        },
        {
            "key": "system_alert",
            "display_name": "System Alert",
            "title_template": "{title}",
            "body_template": "{message}",
            "is_active": True,
            "supports_push": True,
            "supports_email": True,
            "supports_websocket": True,
        },
    ]

    for nt_data in notification_types:
        NotificationType.objects.get_or_create(
            key=nt_data["key"],
            defaults=nt_data,
        )


def reverse_seed(apps, schema_editor):
    """
    Remove seeded notification types.

    Only removes the types seeded by this migration.
    Notifications using these types will prevent deletion (PROTECT).
    """
    NotificationType = apps.get_model("notifications", "NotificationType")
    NotificationType.objects.filter(
        key__in=["welcome", "new_message", "system_alert"]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_notification_types, reverse_seed),
    ]
