# Generated by Django 5.2.9 on 2025-12-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_seed_notification_types"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="notification",
            name="object_id",
            field=models.CharField(
                blank=True,
                help_text="ID of source object (supports UUID and integer PKs)",
                max_length=36,
                null=True,
            ),
        ),
    ]
