# Generated by Django 5.2.9 on 2025-12-19 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_preferences_and_delivery"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("notifications", "0003_notification_object_id_uuid_support"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("push", "Push Notification"),
                            ("email", "Email"),
                            ("websocket", "WebSocket"),
                        ],
                        help_text="Delivery channel",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current delivery status",
                        max_length=20,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notification was sent to the provider",
                        null=True,
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When delivery was confirmed (via webhook)",
                        null=True,
                    ),
                ),
                (
                    "failed_at",
                    models.DateTimeField(
                        blank=True, help_text="When delivery failed", null=True
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Message ID from provider (FCM, SES, etc.) for webhook lookup",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True, default="", help_text="Detailed failure message"
                    ),
                ),
                (
                    "failure_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Error code from provider",
                        max_length=50,
                    ),
                ),
                (
                    "is_permanent_failure",
                    models.BooleanField(
                        default=False,
                        help_text="True if retry won't help (e.g., invalid token)",
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Number of delivery attempts"
                    ),
                ),
                (
                    "skipped_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("global_disabled", "Global notifications disabled"),
                            ("category_disabled", "Category disabled"),
                            ("type_disabled", "Type disabled"),
                            ("channel_disabled", "Channel disabled by user"),
                            ("no_device_token", "No device token"),
                            ("no_email", "No email address"),
                            ("no_connections", "No active connections"),
                        ],
                        default="",
                        help_text="Reason if status=SKIPPED",
                        max_length=30,
                    ),
                ),
                (
                    "websocket_devices_targeted",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Number of WebSocket connections targeted"
                    ),
                ),
                (
                    "websocket_devices_reached",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Number of WebSocket connections that received the message",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification delivery",
                "verbose_name_plural": "notification deliveries",
                "db_table": "notifications_notification_delivery",
            },
        ),
        migrations.CreateModel(
            name="UserCategoryPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("transactional", "Transactional"),
                            ("social", "Social"),
                            ("marketing", "Marketing"),
                            ("system", "System"),
                        ],
                        help_text="Notification category",
                        max_length=20,
                    ),
                ),
                (
                    "disabled",
                    models.BooleanField(
                        default=False,
                        help_text="Disable all notifications in this category",
                    ),
                ),
            ],
            options={
                "verbose_name": "user category preference",
                "verbose_name_plural": "user category preferences",
                "db_table": "notifications_user_category_preference",
            },
        ),
        migrations.CreateModel(
            name="UserGlobalPreference",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="notification_global_preference",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "all_disabled",
                    models.BooleanField(
                        default=False,
                        help_text="Master switch to disable all notifications",
                    ),
                ),
            ],
            options={
                "verbose_name": "user global preference",
                "verbose_name_plural": "user global preferences",
                "db_table": "notifications_user_global_preference",
            },
        ),
        migrations.CreateModel(
            name="UserNotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified",
                    ),
                ),
                (
                    "disabled",
                    models.BooleanField(
                        default=False,
                        help_text="Disable all channels for this notification type",
                    ),
                ),
                (
                    "push_enabled",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="Override push preference (null = use type default)",
                        null=True,
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="Override email preference (null = use type default)",
                        null=True,
                    ),
                ),
                (
                    "websocket_enabled",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="Override websocket preference (null = use type default)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "user notification preference",
                "verbose_name_plural": "user notification preferences",
                "db_table": "notifications_user_notification_preference",
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                help_text="Idempotency key to prevent duplicate notifications",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notificationtype",
            name="category",
            field=models.CharField(
                choices=[
                    ("transactional", "Transactional"),
                    ("social", "Social"),
                    ("marketing", "Marketing"),
                    ("system", "System"),
                ],
                db_index=True,
                default="transactional",
                help_text="Category for preference grouping",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=["idempotency_key"],
                name="notif_idempotency_key_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("idempotency_key",),
                name="notif_idempotency_key_unique",
            ),
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="notification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="notifications.notification",
            ),
        ),
        migrations.AddField(
            model_name="usercategorypreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_category_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="notification_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_preferences",
                to="notifications.notificationtype",
            ),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_type_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["status", "channel", "-created_at"],
                name="notif_delivery_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                condition=models.Q(("provider_message_id__isnull", False)),
                fields=["provider_message_id"],
                name="notif_delivery_provider_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationdelivery",
            constraint=models.UniqueConstraint(
                fields=("notification", "channel"), name="unique_notification_channel"
            ),
        ),
        migrations.AddIndex(
            model_name="usercategorypreference",
            index=models.Index(
                fields=["user", "category"], name="notif_cat_pref_user_cat_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="usercategorypreference",
            constraint=models.UniqueConstraint(
                fields=("user", "category"), name="unique_user_category_pref"
            ),
        ),
        migrations.AddIndex(
            model_name="usernotificationpreference",
            index=models.Index(
                fields=["user", "notification_type"],
                name="notif_type_pref_user_type_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="usernotificationpreference",
            constraint=models.UniqueConstraint(
                fields=("user", "notification_type"), name="unique_user_notif_type_pref"
            ),
        ),
    ]
