# Generated by Django 5.2.9 on 2026-01-02 18:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('photo', models.ImageField(upload_to='')),
                ('visibility', models.CharField(choices=[('PU', 'Public'), ('FR', 'Friends'), ('PR', 'Private')], default='PU', max_length=2)),
                ('taken_at', models.DateTimeField()),
                ('is_draft', models.BooleanField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='User this post belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='UserPost', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_posts.userpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='uniq_user_post_like')],
            },
        ),
    ]
