# Generated by Django 5.2.9 on 2026-01-05 04:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='userpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, help_text='Timestamp when this record was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last modified'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
