# Generated by Django 5.2.9 on 2026-01-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_posts', '0002_alter_userpost_options_userpost_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='h3_r4',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userpost',
            name='h3_r6',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userpost',
            name='h3_r9',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
