# Generated by Django 5.2.9 on 2025-12-12 23:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LedgerAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("user_balance", "User Balance"),
                            ("platform_escrow", "Platform Escrow"),
                            ("platform_revenue", "Platform Revenue"),
                            ("external_stripe", "External Stripe"),
                        ],
                        help_text="Category of this account",
                        max_length=50,
                    ),
                ),
                (
                    "owner_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="UUID of the entity that owns this account (e.g., user ID)",
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="usd", help_text="ISO 4217 currency code", max_length=3
                    ),
                ),
                (
                    "allow_negative",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this account can have a negative balance",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this account is active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this account was created",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["type", "currency"], name="payments_le_type_356483_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("type", "owner_id", "currency"),
                        name="unique_account_per_owner",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this entry was recorded",
                    ),
                ),
                (
                    "amount_cents",
                    models.PositiveBigIntegerField(
                        help_text="Amount in cents (always positive)"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="usd", help_text="ISO 4217 currency code", max_length=3
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("payment_received", "Payment Received"),
                            ("payment_released", "Payment Released"),
                            ("fee_collected", "Fee Collected"),
                            ("payout", "Payout"),
                            ("refund", "Refund"),
                            ("adjustment", "Adjustment"),
                            ("transfer", "Transfer"),
                        ],
                        help_text="Category of this entry",
                        max_length=50,
                    ),
                ),
                (
                    "reference_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of related business entity (e.g., booking ID)",
                        null=True,
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of related entity (e.g., 'booking', 'payment_intent')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable description of this entry",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary JSON data for extensibility",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="Identifier of service/user that created this entry",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        help_text="Unique key to prevent duplicate entries",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "credit_account",
                    models.ForeignKey(
                        help_text="Account money is added to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_entries",
                        to="payments.ledgeraccount",
                    ),
                ),
                (
                    "debit_account",
                    models.ForeignKey(
                        help_text="Account money is taken from",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="debit_entries",
                        to="payments.ledgeraccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["reference_type", "reference_id"],
                        name="payments_le_referen_890278_idx",
                    ),
                    models.Index(
                        fields=["entry_type"], name="payments_le_entry_t_d66fa1_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount_cents__gt", 0)),
                        name="ledger_entry_amount_cents_positive",
                    )
                ],
            },
        ),
    ]
