# Generated by Django 5.2.9 on 2025-12-15 03:32

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_add_expired_holds_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentorder",
            name="refunded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When first refund was processed (full or partial)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When payout was cancelled (e.g., for refund processing)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payout",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("pending", "Pending"),
                    ("scheduled", "Scheduled"),
                    ("processing", "Processing"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                help_text="Current state of the payout (managed by FSM)",
                max_length=50,
                protected=True,
            ),
        ),
    ]
