# Generated by Django 5.2.9 on 2025-12-15 04:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_add_refund_service_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReconciliationRun",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        help_text="When this reconciliation run started"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this reconciliation run completed (or failed)",
                        null=True,
                    ),
                ),
                (
                    "lookback_hours",
                    models.PositiveIntegerField(
                        help_text="How many hours back this run checked"
                    ),
                ),
                (
                    "stuck_threshold_hours",
                    models.PositiveIntegerField(
                        help_text="Threshold for considering records 'stuck'"
                    ),
                ),
                (
                    "payment_orders_checked",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of PaymentOrder records checked"
                    ),
                ),
                (
                    "payouts_checked",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of Payout records checked"
                    ),
                ),
                (
                    "discrepancies_found",
                    models.PositiveIntegerField(
                        default=0, help_text="Total discrepancies found"
                    ),
                ),
                (
                    "auto_healed",
                    models.PositiveIntegerField(
                        default=0, help_text="Discrepancies automatically healed"
                    ),
                ),
                (
                    "flagged_for_review",
                    models.PositiveIntegerField(
                        default=0, help_text="Discrepancies requiring manual review"
                    ),
                ),
                (
                    "failed_to_heal",
                    models.PositiveIntegerField(
                        default=0, help_text="Discrepancies that failed to heal"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="running",
                        help_text="Current status of this reconciliation run",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if the run failed"
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "started_at"],
                        name="payments_re_status_c5d010_idx",
                    ),
                    models.Index(
                        fields=["started_at"], name="payments_re_started_e74ddc_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReconciliationDiscrepancy",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of entity (payment_order or payout)",
                        max_length=50,
                    ),
                ),
                ("entity_id", models.UUIDField(help_text="ID of the affected entity")),
                (
                    "stripe_id",
                    models.CharField(
                        blank=True,
                        help_text="Related Stripe object ID (pi_xxx, tr_xxx)",
                        max_length=255,
                    ),
                ),
                (
                    "discrepancy_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of discrepancy detected (e.g., stripe_transfer_paid_local_processing)",
                        max_length=100,
                    ),
                ),
                (
                    "local_state",
                    models.CharField(
                        help_text="State of the local record when discrepancy was detected",
                        max_length=50,
                    ),
                ),
                (
                    "stripe_state",
                    models.CharField(
                        blank=True,
                        help_text="State/status reported by Stripe",
                        max_length=50,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context about the discrepancy",
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("auto_healed", "Auto Healed"),
                            ("flagged_for_review", "Flagged for Review"),
                            ("manually_resolved", "Manually Resolved"),
                            ("failed_to_heal", "Failed to Heal"),
                        ],
                        db_index=True,
                        help_text="How this discrepancy was resolved",
                        max_length=20,
                    ),
                ),
                (
                    "action_taken",
                    models.TextField(
                        blank=True,
                        help_text="Description of what action was taken to resolve",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if healing failed"
                    ),
                ),
                (
                    "reviewed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether a human has reviewed this discrepancy",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this discrepancy was reviewed",
                        null=True,
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, help_text="Notes from the reviewer"),
                ),
                (
                    "ledger_entry_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of ledger entry created for this correction (if any)",
                        null=True,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who reviewed this discrepancy",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_discrepancies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        help_text="The reconciliation run that found this discrepancy",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discrepancies",
                        to="payments.reconciliationrun",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Reconciliation discrepancies",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["resolution", "reviewed"],
                        name="payments_re_resolut_b53ab9_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="payments_re_entity__9392ca_idx",
                    ),
                    models.Index(
                        fields=["discrepancy_type"],
                        name="payments_re_discrep_8f6ad4_idx",
                    ),
                    models.Index(
                        fields=["run", "resolution"],
                        name="payments_re_run_id_5de2e4_idx",
                    ),
                ],
            },
        ),
    ]
