# Generated by Django 5.2.9 on 2025-12-15 05:20

import django.db.models.deletion
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0005_reconciliation_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentorder",
            name="stripe_invoice_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Stripe Invoice ID (in_xxx) - for subscription payments",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this record",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recipient_profile_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Profile UUID of the subscription recipient (mentor)",
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        db_index=True,
                        help_text="Stripe Subscription ID (sub_xxx)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        db_index=True,
                        help_text="Stripe Customer ID (cus_xxx)",
                        max_length=255,
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        help_text="Stripe Price ID (price_xxx)", max_length=255
                    ),
                ),
                (
                    "amount_cents",
                    models.PositiveBigIntegerField(
                        help_text="Subscription amount in smallest currency unit (e.g., cents)"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="usd",
                        help_text="ISO 4217 currency code (lowercase)",
                        max_length=3,
                    ),
                ),
                (
                    "billing_interval",
                    models.CharField(
                        default="month",
                        help_text="Billing frequency: 'month' or 'year'",
                        max_length=10,
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current state of the subscription (managed by FSM)",
                        max_length=50,
                        protected=True,
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start of current billing period",
                        null=True,
                    ),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(
                        blank=True, help_text="End of current billing period", null=True
                    ),
                ),
                (
                    "cancel_at_period_end",
                    models.BooleanField(
                        default=False,
                        help_text="Whether subscription will cancel at period end",
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When subscription was cancelled",
                        null=True,
                    ),
                ),
                (
                    "last_invoice_id",
                    models.CharField(
                        blank=True,
                        help_text="Most recent Stripe invoice ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "last_payment_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When last successful payment occurred",
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Version for optimistic locking - incremented on each save",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary JSON metadata for extensibility",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        help_text="User paying for the subscription",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="Subscription this payment belongs to (for recurring payments)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_orders",
                to="payments.subscription",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentorder",
            index=models.Index(
                fields=["subscription", "state"], name="payments_pa_subscri_218877_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["payer", "state"], name="payments_su_payer_i_7ae40f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["recipient_profile_id", "state"],
                name="payments_su_recipie_83d3ad_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["stripe_customer_id"], name="payments_su_stripe__e03011_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["state", "current_period_end"],
                name="payments_su_state_d7697c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_cents__gt", 0)),
                name="subscription_amount_positive",
            ),
        ),
    ]
