# Generated by Django 5.2.9 on 2025-12-15 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0006_subscription_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payout",
            name="payment_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Payment order this payout originates from. Null for aggregated payouts.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payouts",
                to="payments.paymentorder",
            ),
        ),
    ]
