# Generated by Django 5.2.9 on 2025-12-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0007_allow_null_payment_order_for_aggregated_payouts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="recipient_profile_id",
            field=models.UUIDField(
                db_index=True, help_text="Profile UUID of the subscription recipient"
            ),
        ),
    ]
